import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import { CHARACTER_WRISTS_TYPE } from "./types";

export const wrists_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const wrists_lace_stylemap = [
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.YELLOW
]

export const wrists_feature: CharacterFeature = {
  [CHARACTER_WRISTS_TYPE.NONE]: {
    variant: CHARACTER_WRISTS_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_WRISTS_TYPE.WRISTS]: {
    variant: CHARACTER_WRISTS_TYPE.WRISTS,
    stylemap: wrists_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
      ],
    },
  },
  [CHARACTER_WRISTS_TYPE.LACE]: {
    variant: CHARACTER_WRISTS_TYPE.LACE,
    stylemap: wrists_lace_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
      ],
    },
  },
};
