import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import { CHARACTER_MUSTACHE_TYPE } from "./types";

export const mustache_stylemap = [
  CHARACTER_STYLE.BLONDE,
  CHARACTER_STYLE.ASH,
  CHARACTER_STYLE.SANDY,
  CHARACTER_STYLE.PLATINUM,
  CHARACTER_STYLE.STRAWBERRY,
  CHARACTER_STYLE.REDHEAD,
  CHARACTER_STYLE.GINGER,
  CHARACTER_STYLE.CARROT,
  CHARACTER_STYLE.CHESTNUT,
  CHARACTER_STYLE.LIGHT_BROWN,
  CHARACTER_STYLE.DARK_BROWN,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.RAVEN,
  CHARACTER_STYLE.DARK_GRAY,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.VIOLET,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.ROSE,
];

export const mustache_feature: CharacterFeature = {
  [CHARACTER_MUSTACHE_TYPE.NONE]: {
    variant: CHARACTER_MUSTACHE_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_MUSTACHE_TYPE.BIG]: {
    variant: CHARACTER_MUSTACHE_TYPE.BIG,
    stylemap: mustache_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_MUSTACHE_TYPE.BASIC]: {
    variant: CHARACTER_MUSTACHE_TYPE.BASIC,
    stylemap: mustache_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_MUSTACHE_TYPE.FRENCH]: {
    variant: CHARACTER_MUSTACHE_TYPE.FRENCH,
    stylemap: mustache_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_MUSTACHE_TYPE.WALRUS]: {
    variant: CHARACTER_MUSTACHE_TYPE.WALRUS,
    stylemap: mustache_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_MUSTACHE_TYPE.CHEVRON]: {
    variant: CHARACTER_MUSTACHE_TYPE.CHEVRON,
    stylemap: mustache_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_MUSTACHE_TYPE.HANDLEBAR]: {
    variant: CHARACTER_MUSTACHE_TYPE.HANDLEBAR,
    stylemap: mustache_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_MUSTACHE_TYPE.LAMPSHADE]: {
    variant: CHARACTER_MUSTACHE_TYPE.LAMPSHADE,
    stylemap: mustache_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_MUSTACHE_TYPE.HORSESHOE]: {
    variant: CHARACTER_MUSTACHE_TYPE.HORSESHOE,
    stylemap: mustache_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
};
