import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import {
  CHARACTER_JACKET_TYPE,
  CHARACTER_JACKET_COLLAR_TYPE,
  CHARACTER_JACKET_TRIM_TYPE,
  CHARACTER_JACKET_POCKETS_TYPE,
} from "./types";

export const jacket_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const jacket_collared_stylemap = [
  CHARACTER_STYLE.BROWN_STRIPED,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const jacket_iverness_stylemap = [CHARACTER_STYLE.BLACK];

export const jacket_trench_stylemap = [
  CHARACTER_STYLE.DARK_GRAY,
  CHARACTER_STYLE.GRAY,
];

export const jacket_feature: CharacterFeature = {
  [CHARACTER_JACKET_TYPE.NONE]: {
    variant: CHARACTER_JACKET_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_JACKET_TYPE.COLLARED]: {
    variant: CHARACTER_JACKET_TYPE.COLLARED,
    stylemap: jacket_collared_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
  [CHARACTER_JACKET_TYPE.IVERNESS]: {
    variant: CHARACTER_JACKET_TYPE.IVERNESS,
    stylemap: jacket_iverness_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
  [CHARACTER_JACKET_TYPE.TRENCH]: {
    variant: CHARACTER_JACKET_TYPE.TRENCH,
    stylemap: jacket_trench_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
  [CHARACTER_JACKET_TYPE.TABARD]: {
    variant: CHARACTER_JACKET_TYPE.TABARD,
    stylemap: jacket_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_JACKET_TYPE.FROCK]: {
    variant: CHARACTER_JACKET_TYPE.FROCK,
    stylemap: jacket_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
  [CHARACTER_JACKET_TYPE.SANTA]: {
    variant: CHARACTER_JACKET_TYPE.SANTA,
    stylemap: jacket_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
};

export const jacket_collar_stylemap = [
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.YELLOW,
];

export const jacket_collar_feature: CharacterFeature = {
  [CHARACTER_JACKET_COLLAR_TYPE.NONE]: {
    variant: CHARACTER_JACKET_COLLAR_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_JACKET_COLLAR_TYPE.FROCK]: {
    variant: CHARACTER_JACKET_COLLAR_TYPE.FROCK,
    stylemap: jacket_collar_stylemap,
    required: {
      [CHARACTER_FEATURE.JACKET]: [CHARACTER_JACKET_TYPE.FROCK],
    },
  },
};

export const jacket_trim_stylemap = [
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.YELLOW,
];

export const jacket_trim_feature: CharacterFeature = {
  [CHARACTER_JACKET_TRIM_TYPE.NONE]: {
    variant: CHARACTER_JACKET_TRIM_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_JACKET_TRIM_TYPE.FROCK_LACE]: {
    variant: CHARACTER_JACKET_TRIM_TYPE.FROCK_LACE,
    stylemap: jacket_trim_stylemap,
    required: {
      [CHARACTER_FEATURE.JACKET]: [CHARACTER_JACKET_TYPE.FROCK],
    },
  },
  [CHARACTER_JACKET_TRIM_TYPE.FROCK_LAPEL]: {
    variant: CHARACTER_JACKET_TRIM_TYPE.FROCK_LAPEL,
    stylemap: jacket_trim_stylemap,
    required: {
      [CHARACTER_FEATURE.JACKET]: [CHARACTER_JACKET_TYPE.FROCK],
    },
  },
  [CHARACTER_JACKET_TRIM_TYPE.FROCK_BUTTONS]: {
    variant: CHARACTER_JACKET_TRIM_TYPE.FROCK_BUTTONS,
    stylemap: jacket_trim_stylemap,
    required: {
      [CHARACTER_FEATURE.JACKET]: [CHARACTER_JACKET_TYPE.FROCK],
    },
  },
};

export const jacket_pockets_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const jacket_pockets_feature: CharacterFeature = {
  [CHARACTER_JACKET_POCKETS_TYPE.NONE]: {
    variant: CHARACTER_JACKET_POCKETS_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_JACKET_POCKETS_TYPE.POCKETS]: {
    variant: CHARACTER_JACKET_POCKETS_TYPE.POCKETS,
    stylemap: jacket_pockets_stylemap,
    required: {
      [CHARACTER_FEATURE.JACKET]: [CHARACTER_JACKET_TYPE.FROCK],
    },
  },
};
