import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import { CHARACTER_LEGS_TYPE } from "./types";

export const legs_armour_stylemap = [
  CHARACTER_STYLE.STEEL,
  CHARACTER_STYLE.IRON,
  CHARACTER_STYLE.CERAMIC,
  CHARACTER_STYLE.BRASS,
  CHARACTER_STYLE.COPPER,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.GOLD,
];

export const legs_wide_pants_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.WHITE,
];

export const legs_pants_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const legs_pantaloons_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.FORMAL,
  CHARACTER_STYLE.FORMAL_STRIPED,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const legs_pregnancy_pants_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const legs_child_pants_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.DARK_BLUE,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LIGHT_BLUE,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.WHITE,
];

export const legs_child_skirt_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.DARK_BLUE,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LIGHT_BLUE,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.WHITE,
];

export const legs_feature: CharacterFeature = {
  [CHARACTER_LEGS_TYPE.NONE]: {
    variant: CHARACTER_LEGS_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_LEGS_TYPE.ARMOUR]: {
    variant: CHARACTER_LEGS_TYPE.ARMOUR,
    stylemap: legs_armour_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_LEGS_TYPE.WIDE_PANTS]: {
    variant: CHARACTER_LEGS_TYPE.WIDE_PANTS,
    stylemap: legs_wide_pants_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MUSCULAR],
    },
  },
  [CHARACTER_LEGS_TYPE.PANTS]: {
    variant: CHARACTER_LEGS_TYPE.PANTS,
    stylemap: legs_pants_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_LEGS_TYPE.PANTALOONS]: {
    variant: CHARACTER_LEGS_TYPE.PANTALOONS,
    stylemap: legs_pantaloons_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
  [CHARACTER_LEGS_TYPE.LEGGINGS]: {
    variant: CHARACTER_LEGS_TYPE.LEGGINGS,
    stylemap: legs_pants_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
      ],
    },
  },
  [CHARACTER_LEGS_TYPE.PREGNANCY_PANTS]: {
    variant: CHARACTER_LEGS_TYPE.PREGNANCY_PANTS,
    stylemap: legs_pregnancy_pants_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.PREGNANT],
    },
  },
  [CHARACTER_LEGS_TYPE.CHILD_PANTS]: {
    variant: CHARACTER_LEGS_TYPE.CHILD_PANTS,
    stylemap: legs_child_pants_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_LEGS_TYPE.CHILD_SKIRT]: {
    variant: CHARACTER_LEGS_TYPE.CHILD_SKIRT,
    stylemap: legs_child_skirt_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_LEGS_TYPE.PLAIN_SKIRT]: {
    variant: CHARACTER_LEGS_TYPE.PLAIN_SKIRT,
    stylemap: legs_pants_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
      ],
    },
  },
  [CHARACTER_LEGS_TYPE.SLIT_SKIRT]: {
    variant: CHARACTER_LEGS_TYPE.SLIT_SKIRT,
    stylemap: legs_pants_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
      ],
    },
  },
  [CHARACTER_LEGS_TYPE.LEGION_SKIRT]: {
    variant: CHARACTER_LEGS_TYPE.LEGION_SKIRT,
    stylemap: legs_pants_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_LEGS_TYPE.STRAIGHT_SKIRT]: {
    variant: CHARACTER_LEGS_TYPE.STRAIGHT_SKIRT,
    stylemap: legs_pants_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
      ],
    },
  },
  [CHARACTER_LEGS_TYPE.BELLE_SKIRT]: {
    variant: CHARACTER_LEGS_TYPE.BELLE_SKIRT,
    stylemap: legs_pants_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
      ],
    },
  },
};
