export enum CHARACTER_HAT_TYPE {
  NONE = "",
  FORMAL = "formal",
  REPTILE = "reptile",
  MAGIC = "magic",
  CLOTH = "cloth",

  HELMETS_ARMET = "helmets_armet",
  HELMETS_SIMPLE_ARMET = "helmets_simple_armet",
  HELMETS_BARBARIAN = "helmets_barbarian",
  HELMETS_BARBARIAN_NASAL = "helmets_barbarian_nasal",
  HELMETS_BARBARIAN_VIKING = "helmets_barbarian_viking",
  HELMETS_BARBUTA = "helmets_barbuta",
  HELMETS_SIMPLE_BARBUTA = "helmets_simple_barbuta",
  HELMETS_BASCINET = "helmets_bascinet",
  HELMETS_PIGFACE_BASCINET = "helmets_pigface_bascinet",
  HELMETS_PIGFACE_BASCINET_RAISED = "helmets_pigface_bascinet_raised",
  HELMETS_ROUND_BASCINET = "helmets_round_bascinet",
  HELMETS_ROUND_BASCINET_RAISED = "helmets_round_bascinet_raised",
  HELMETS_CLOSE_HELM = "helmets_close_helm",
  HELMETS_FLATTOP = "helmets_flattop",
  HELMETS_GREATHELM = "helmets_greathelm",
  HELMETS_HORNED_HELMET = "helmets_horned_helmet",
  HELMETS_KETTLE_HELM = "helmets_kettle_helm",
  HELMETS_LEGION = "helmets_legion",
  HELMETS_MAXIMUS = "helmets_maximus",
  HELMETS_MORION = "helmets_morion",
  HELMETS_NASAL_HELM = "helmets_nasal_helm",
  HELMETS_NORMAN_HELM = "helmets_norman_helm",
  HELMETS_POINTED_HELM = "helmets_pointed_helm",
  HELMETS_SPANGENHELM = "helmets_spangenhelm",
  HELMETS_VIKING_SPANGENHELM = "helmets_viking_spangenhelm",
  HELMETS_SUGARLOAF_GREATHELM = "helmets_sugarloaf_greathelm",
  HELMETS_SIMPLE_SUGARLOAF_GREATHELM = "helmets_simple_sugarloaf_greathelm",
  HELMETS_XEON_HELMET = "helmets_xeon_helmet",

  PIRATE_BONNIE = "pirate_bonnie",
  PIRATE_BONNIE_FEATHER = "pirate_bonnie_feather",
  PIRATE_CAVALIER = "pirate_cavalier",
  PIRATE_CAVALIER_FEATHER = "pirate_cavalier_feather",
  PIRATE_TRICORNE = "pirate_tricorne",
  PIRATE_TRICORNE_STITCHED = "pirate_tricorne_stitched",
  PIRATE_TRICORNE_THATCH = "pirate_tricorne_thatch",
  PIRATE_TRICORNE_PIRATE_CAPTAIN = "pirate_tricorne_pirate_captain",
  PIRATE_TRICORNE_LIEUTENANT = "pirate_tricorne_lieutenant",
  PIRATE_TRICORNE_CAPTAIN = "pirate_tricorne_captain",
  PIRATE_BICORNE_ATHWART = "pirate_bicorne_athwart",
  PIRATE_BICORNE_ATHWART_PIRATE = "pirate_bicorne_athwart_pirate",
  PIRATE_BICORNE_ATHWART_ADMIRAL = "pirate_bicorne_athwart_admiral",
  PIRATE_BICORNE_ATHWART_ADMIRAL_COCKADE = "pirate_bicorne_athwart_admiral_cockade",
  PIRATE_BICORNE_ATHWART_COMMODORE = "pirate_bicorne_athwart_commodore",
  PIRATE_BICORNE_FOREAFT = "pirate_bicorne_foreaft",
  PIRATE_BICORNE_FOREAFT_COMMODORE = "pirate_bicorne_foreaft_commodore",

  CROWN = "crown",
  CROWN_TIARA = "crown_tiara",

  SPECIAL_SANTA = "special_santa",
  SPECIAL_ELF = "special_elf",
}

export enum CHARACTER_VISOR_TYPE {
  NONE = "",
  GRATED_VISOR = "grated_visor",
  NARROW_GRATED_VISOR = "narrow_grated_visor",
  HORNED_VISOR = "horned_visor",
  PIGFACE_VISOR = "pigface_visor",
  PIGFACE_VISOR_RAISED = "pigface_visor_raised",
  ROUND_VISOR = "round_visor",
  ROUND_VISOR_RAISED = "round_visor_raised",
  SLIT_VISOR = "_slit_visor",
  NARROW_SLIT_VISOR = "_narrow_slit_visor",

}