import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import { CHARACTER_VEST_TYPE } from "./types";

export const vest1_stylemap = [
  CHARACTER_STYLE.GRAY_STRIPED,
  CHARACTER_STYLE.GREEN_STRIPED,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const vest2_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const vest_corset_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const vest_feature: CharacterFeature = {
  [CHARACTER_VEST_TYPE.NONE]: {
    variant: CHARACTER_VEST_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_VEST_TYPE.BODICE]: {
    variant: CHARACTER_VEST_TYPE.BODICE,
    stylemap: vest2_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.FEMALE],
    },
  },
  [CHARACTER_VEST_TYPE.CORSET]: {
    variant: CHARACTER_VEST_TYPE.CORSET,
    stylemap: vest_corset_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.FEMALE],
    },
  },
  [CHARACTER_VEST_TYPE.VEST]: {
    variant: CHARACTER_VEST_TYPE.VEST,
    stylemap: vest1_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
  [CHARACTER_VEST_TYPE.VEST_OPEN]: {
    variant: CHARACTER_VEST_TYPE.VEST_OPEN,
    stylemap: vest2_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
};
