import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import { CHARACTER_SHOULDERS_TYPE } from "./types";

export const shoulders_legion_stylemap = [
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.STEEL,
  CHARACTER_STYLE.GOLD,
];

export const shoulders_plate_stylemap = [
  CHARACTER_STYLE.STEEL,
  CHARACTER_STYLE.IRON,
  CHARACTER_STYLE.CERAMIC,
  CHARACTER_STYLE.BRASS,
  CHARACTER_STYLE.COPPER,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.GOLD,
];

export const shoulders_leather_stylemap = [
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const shoulders_epaulets_stylemap = [
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.YELLOW,
];

export const shoulders_mantal_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const shoulders_feature: CharacterFeature = {
  [CHARACTER_SHOULDERS_TYPE.NONE]: {
    variant: CHARACTER_SHOULDERS_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_SHOULDERS_TYPE.LEGION]: {
    variant: CHARACTER_SHOULDERS_TYPE.LEGION,
    stylemap: shoulders_legion_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_SHOULDERS_TYPE.PLATE]: {
    variant: CHARACTER_SHOULDERS_TYPE.PLATE,
    stylemap: shoulders_plate_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_SHOULDERS_TYPE.LEATHER]: {
    variant: CHARACTER_SHOULDERS_TYPE.LEATHER,
    stylemap: shoulders_leather_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_SHOULDERS_TYPE.EPAULETS]: {
    variant: CHARACTER_SHOULDERS_TYPE.EPAULETS,
    stylemap: shoulders_epaulets_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
  [CHARACTER_SHOULDERS_TYPE.MANTAL]: {
    variant: CHARACTER_SHOULDERS_TYPE.MANTAL,
    stylemap: shoulders_mantal_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
};
