import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import {CHARACTER_EYEBROWS_TYPE, CHARACTER_EYES_TYPE} from './types';

export const eyes_stylemap = [
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.YELLOW,
];

export const eyes_cyclops_stylemap = [
  CHARACTER_STYLE.CYCLOPS,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.YELLOW,
];

export const eyes_feature: CharacterFeature = {
  [CHARACTER_EYES_TYPE.HUMAN]: {
    variant: CHARACTER_EYES_TYPE.HUMAN,
    stylemap: eyes_stylemap,
    required: {},
  },
  [CHARACTER_EYES_TYPE.CYCLOPS]: {
    variant: CHARACTER_EYES_TYPE.CYCLOPS,
    stylemap: eyes_cyclops_stylemap,
    required: {},
  },
};

export const eyebrows_stylemap = [
  CHARACTER_STYLE.BLONDE,
  CHARACTER_STYLE.ASH,
  CHARACTER_STYLE.SANDY,
  CHARACTER_STYLE.PLATINUM,
  CHARACTER_STYLE.STRAWBERRY,
  CHARACTER_STYLE.REDHEAD,
  CHARACTER_STYLE.GINGER,
  CHARACTER_STYLE.CARROT,
  CHARACTER_STYLE.CHESTNUT,
  CHARACTER_STYLE.LIGHT_BROWN,
  CHARACTER_STYLE.DARK_BROWN,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.RAVEN,
  CHARACTER_STYLE.DARK_GRAY,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.VIOLET,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.ROSE,
];

export const eyebrows_feature: CharacterFeature = {
  [CHARACTER_EYEBROWS_TYPE.NONE]: {
    variant: CHARACTER_EYEBROWS_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_EYEBROWS_TYPE.THICK]: {
    variant: CHARACTER_EYEBROWS_TYPE.THICK,
    stylemap: eyebrows_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_EYEBROWS_TYPE.THIN]: {
    variant: CHARACTER_EYEBROWS_TYPE.THIN,
    stylemap: eyebrows_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
};
