-- Migration to change OAuth connections from avatar-based to document-based
-- Drop foreign key constraint for avatarId
DO $$ BEGIN
 ALTER TABLE "OAuthConnection" DROP CONSTRAINT IF EXISTS "OAuthConnection_avatarId_Avatar_id_fk";
EXCEPTION
 WHEN undefined_object THEN null;
END $$;

-- Drop avatarId column
ALTER TABLE "OAuthConnection" DROP COLUMN IF EXISTS "avatarId";

-- Add documentId column
ALTER TABLE "OAuthConnection" ADD COLUMN "documentId" uuid;

-- Add foreign key constraint for documentId
DO $$ BEGIN
 ALTER TABLE "OAuthConnection" ADD CONSTRAINT "OAuthConnection_documentId_Document_id_fk" FOREIGN KEY ("documentId") REFERENCES "public"."Document"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

-- Update meta journal
-- Note: This would normally be generated by drizzle-kit
-- Manual update to indicate the migration was applied 