import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import {
  CHARACTER_SHIELD_TYPE,
  CHARACTER_SHIELD_PAINT_TYPE,
  CHARACTER_SHIELD_PATTERN_TYPE,
  CHARACTER_SHIELD_TRIM_TYPE,
} from "./types";

export const shield_stylemap = [
  CHARACTER_STYLE.CRUSADER,
  CHARACTER_STYLE.SPARTAN,
  CHARACTER_STYLE.ROUND_BLACK,
  CHARACTER_STYLE.ROUND_BROWN,
  CHARACTER_STYLE.ROUND_GOLD,
  CHARACTER_STYLE.ROUND_GREEN,
  CHARACTER_STYLE.ROUND_SILVER,
  CHARACTER_STYLE.ROUND_YELLOW,
  CHARACTER_STYLE.KITE_BLUE_BLUE,
  CHARACTER_STYLE.KITE_BLUE_GRAY,
  CHARACTER_STYLE.KITE_GRAY_BLUE,
  CHARACTER_STYLE.KITE_GRAY_GRAY,
  CHARACTER_STYLE.KITE_GRAY_GREEN,
  CHARACTER_STYLE.KITE_GRAY_ORANGE,
  CHARACTER_STYLE.KITE_GRAY,
  CHARACTER_STYLE.KITE_GREEN_GRAY,
  CHARACTER_STYLE.KITE_ORANGE,
  CHARACTER_STYLE.KITE_RED_GRAY,
];

export const shield_spartan_stylemap = [CHARACTER_STYLE.SPARTAN];

export const shield_two_engrailed_stylemap = [CHARACTER_STYLE.TWO_ENGRAILED];

export const shield_crusader_stylemap = [CHARACTER_STYLE.CRUSADER];

export const shield_plus_stylemap = [CHARACTER_STYLE.PLUS];

export const shield_scutum_stylemap = [CHARACTER_STYLE.SCUTUM];

export const shield_heater_wood_stylemap = [
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.COFFEE,
  CHARACTER_STYLE.OAK,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.UMBER,
];

export const shield_feature: CharacterFeature = {
  [CHARACTER_SHIELD_TYPE.NONE]: {
    variant: CHARACTER_SHIELD_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_SHIELD_TYPE.SHIELD]: {
    variant: CHARACTER_SHIELD_TYPE.SHIELD,
    stylemap: shield_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_SHIELD_TYPE.SPARTAN]: {
    variant: CHARACTER_SHIELD_TYPE.SPARTAN,
    stylemap: shield_spartan_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_SHIELD_TYPE.TWO_ENGRAILED]: {
    variant: CHARACTER_SHIELD_TYPE.TWO_ENGRAILED,
    stylemap: shield_two_engrailed_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_SHIELD_TYPE.CRUSADER]: {
    variant: CHARACTER_SHIELD_TYPE.CRUSADER,
    stylemap: shield_crusader_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_SHIELD_TYPE.PLUS]: {
    variant: CHARACTER_SHIELD_TYPE.PLUS,
    stylemap: shield_plus_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_SHIELD_TYPE.SCUTUM]: {
    variant: CHARACTER_SHIELD_TYPE.SCUTUM,
    stylemap: shield_scutum_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_SHIELD_TYPE.HEATER]: {
    variant: CHARACTER_SHIELD_TYPE.HEATER,
    stylemap: shield_heater_wood_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
};

export const shiel_trim_two_engrailed_stylemap = [
  CHARACTER_STYLE.TWO_ENGRAILED_TRIM,
];

export const shiel_trim_scutum_stylemap = [CHARACTER_STYLE.SCUTUM_TRIM];

export const shiel_trim_heater_stylemap = [
  CHARACTER_STYLE.BRASS,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.COPPER,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.IRON,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.STEEL,
];

export const shield_trim_feature: CharacterFeature = {
  [CHARACTER_SHIELD_TRIM_TYPE.NONE]: {
    variant: CHARACTER_SHIELD_TRIM_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_SHIELD_TRIM_TYPE.TWO_ENGRAILED]: {
    variant: CHARACTER_SHIELD_TRIM_TYPE.TWO_ENGRAILED,
    stylemap: shiel_trim_two_engrailed_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.TWO_ENGRAILED],
    },
  },
  [CHARACTER_SHIELD_TRIM_TYPE.SCUTUM]: {
    variant: CHARACTER_SHIELD_TRIM_TYPE.SCUTUM,
    stylemap: shiel_trim_scutum_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.SCUTUM],
    },
  },
  [CHARACTER_SHIELD_TRIM_TYPE.HEATER]: {
    variant: CHARACTER_SHIELD_TRIM_TYPE.HEATER,
    stylemap: shiel_trim_heater_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
};

export const shield_paint_heater_stylemap = [
  CHARACTER_STYLE.AEGEAN,
  CHARACTER_STYLE.AMBER,
  CHARACTER_STYLE.AMETHYST,
  CHARACTER_STYLE.APPLE,
  CHARACTER_STYLE.APRICOT,
  CHARACTER_STYLE.AZURE,
  CHARACTER_STYLE.BEIGE,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUE_VIOLET,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CERISE,
  CHARACTER_STYLE.CERULEAN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.CHOCOLATE,
  CHARACTER_STYLE.COFFEE,
  CHARACTER_STYLE.CORAL,
  CHARACTER_STYLE.CORN_FLOWER,
  CHARACTER_STYLE.CYAN,
  CHARACTER_STYLE.DENIM,
  CHARACTER_STYLE.DOVE,
  CHARACTER_STYLE.EMERALD,
  CHARACTER_STYLE.FERN,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GARNET,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.HEATHER,
  CHARACTER_STYLE.HONEY,
  CHARACTER_STYLE.ICE,
  CHARACTER_STYLE.INDIGO,
  CHARACTER_STYLE.IVORY,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.LEMON,
  CHARACTER_STYLE.LINEN,
  CHARACTER_STYLE.MAUVE,
  CHARACTER_STYLE.MIDNIGHT,
  CHARACTER_STYLE.MINT,
  CHARACTER_STYLE.MUSTARD,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.NEPTUNE,
  CHARACTER_STYLE.OAK,
  CHARACTER_STYLE.OCHRE,
  CHARACTER_STYLE.OLIVINE,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PEACH,
  CHARACTER_STYLE.PEARL,
  CHARACTER_STYLE.PERIWINKLE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PLUM,
  CHARACTER_STYLE.PORCELAIN,
  CHARACTER_STYLE.POWDER,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.RED_ORANGE,
  CHARACTER_STYLE.ROYAL,
  CHARACTER_STYLE.SALMON,
  CHARACTER_STYLE.SEPIA,
  CHARACTER_STYLE.SHADOW,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SMOKE,
  CHARACTER_STYLE.SOOT,
  CHARACTER_STYLE.SPRING,
  CHARACTER_STYLE.SWAMP,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TAWNY,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.TUMERIC,
  CHARACTER_STYLE.UMBER,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.WINE,
  CHARACTER_STYLE.YELLOW,
];

export const shield_paint_feature: CharacterFeature = {
  [CHARACTER_SHIELD_PAINT_TYPE.NONE]: {
    variant: CHARACTER_SHIELD_PAINT_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_SHIELD_PAINT_TYPE.HEATER]: {
    variant: CHARACTER_SHIELD_PAINT_TYPE.HEATER,
    stylemap: shield_paint_heater_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
};

export const shield_pattern_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const shield_pattern_feature: CharacterFeature = {
  [CHARACTER_SHIELD_PATTERN_TYPE.NONE]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.BARRY]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.BARRY,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.BEND_SINISTER]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.BEND_SINISTER,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.BEND]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.BEND,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.BENDY_SINISTER]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.BENDY_SINISTER,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.BENDY]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.BENDY,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.BORDURE]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.BORDURE,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.CHEVRON_INVERTED]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.CHEVRON_INVERTED,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.CHEVRON]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.CHEVRON,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.CHIEF]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.CHIEF,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.CROSS]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.CROSS,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.FESS]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.CROSS,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.LOZENGY]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.LOZENGY,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.PALE]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.PALE,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.PALL]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.PALL,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.PALY]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.PALY,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.PER_BEND_SINISTER]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.PER_BEND_SINISTER,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.PER_BEND]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.PER_BEND,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.PER_CHEVRON_INVERTED]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.PER_CHEVRON_INVERTED,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.PER_CHEVRON]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.PER_CHEVRON,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.PER_FESS]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.PER_FESS,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.PER_PALE]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.PER_PALE,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.PER_SALTIRE]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.PER_SALTIRE,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.QUARTERLY]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.QUARTERLY,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
  [CHARACTER_SHIELD_PATTERN_TYPE.SALTIRE]: {
    variant: CHARACTER_SHIELD_PATTERN_TYPE.SALTIRE,
    stylemap: shield_pattern_stylemap,
    required: {
      [CHARACTER_FEATURE.SHIELD]: [CHARACTER_SHIELD_TYPE.HEATER],
    },
  },
};
