import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import { CHARACTER_CLOTH_TYPE } from "./types";

export const cloth_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const cloth_child_tshirt_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LIGHT_BLUE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.WHITE,
];

export const cloth_formal_stylemap = [CHARACTER_STYLE.WHITE];

export const cloth_female_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const cloth_robe_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.DARK_BROWN,
  CHARACTER_STYLE.DARK_GRAY,
  CHARACTER_STYLE.FOREST_GREEN,
  CHARACTER_STYLE.LIGHT_GRAY,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.WHITE,
];

export const cloth_feature: CharacterFeature = {
  [CHARACTER_CLOTH_TYPE.NONE]: {
    variant: CHARACTER_CLOTH_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_CLOTH_TYPE.CHILD_TSHIRT]: {
    variant: CHARACTER_CLOTH_TYPE.CHILD_TSHIRT,
    stylemap: cloth_child_tshirt_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_CLOTH_TYPE.LONGSLEEVE_SHIRT]: {
    variant: CHARACTER_CLOTH_TYPE.LONGSLEEVE_SHIRT,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.SCOOP]: {
    variant: CHARACTER_CLOTH_TYPE.SCOOP,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.PREGNANT,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.COLORED_FORMAL_LONGSLEEVE]: {
    variant: CHARACTER_CLOTH_TYPE.COLORED_FORMAL_LONGSLEEVE,
    stylemap: cloth_formal_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
  [CHARACTER_CLOTH_TYPE.STRIPED_FORMAL_LONGSLEEVE]: {
    variant: CHARACTER_CLOTH_TYPE.STRIPED_FORMAL_LONGSLEEVE,
    stylemap: cloth_formal_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
  [CHARACTER_CLOTH_TYPE.LONGSLEEVE_LACED]: {
    variant: CHARACTER_CLOTH_TYPE.LONGSLEEVE_LACED,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
  [CHARACTER_CLOTH_TYPE.SHORTSLEEVE_SHIRT]: {
    variant: CHARACTER_CLOTH_TYPE.SHORTSLEEVE_SHIRT,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.TSHIRT]: {
    variant: CHARACTER_CLOTH_TYPE.TSHIRT,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.TSHIRT_VNECK]: {
    variant: CHARACTER_CLOTH_TYPE.TSHIRT_VNECK,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.TSHIRT_SCOOP]: {
    variant: CHARACTER_CLOTH_TYPE.TSHIRT_SCOOP,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.TSHIRT_BUTTONED]: {
    variant: CHARACTER_CLOTH_TYPE.TSHIRT_BUTTONED,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.SLEEVELESS_SHIRT]: {
    variant: CHARACTER_CLOTH_TYPE.SLEEVELESS_SHIRT,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.SLEEVELESS_LACED]: {
    variant: CHARACTER_CLOTH_TYPE.SLEEVELESS_LACED,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
  [CHARACTER_CLOTH_TYPE.SLEEVELESS_STRIPED]: {
    variant: CHARACTER_CLOTH_TYPE.SLEEVELESS_STRIPED,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
  [CHARACTER_CLOTH_TYPE.TANKTOP]: {
    variant: CHARACTER_CLOTH_TYPE.TANKTOP,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.PREGNANT,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.SLEEVELESS2]: {
    variant: CHARACTER_CLOTH_TYPE.SLEEVELESS2,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.SLEEVELESS2_VNECK]: {
    variant: CHARACTER_CLOTH_TYPE.SLEEVELESS2_VNECK,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.SLEEVELESS2_SCOOP]: {
    variant: CHARACTER_CLOTH_TYPE.SLEEVELESS2_SCOOP,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.SLEEVELESS2_BUTTONED]: {
    variant: CHARACTER_CLOTH_TYPE.SLEEVELESS2_BUTTONED,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_CLOTH_TYPE.BLOUSE]: {
    variant: CHARACTER_CLOTH_TYPE.BLOUSE,
    stylemap: cloth_female_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.FEMALE],
    },
  },
  [CHARACTER_CLOTH_TYPE.LONGSLEEVE_BLOUSE]: {
    variant: CHARACTER_CLOTH_TYPE.LONGSLEEVE_BLOUSE,
    stylemap: cloth_female_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.FEMALE],
    },
  },
  [CHARACTER_CLOTH_TYPE.TUNIC]: {
    variant: CHARACTER_CLOTH_TYPE.TUNIC,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.FEMALE],
    },
  },
  [CHARACTER_CLOTH_TYPE.SARA_TUNIC]: {
    variant: CHARACTER_CLOTH_TYPE.SARA_TUNIC,
    stylemap: cloth_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.FEMALE],
    },
  },
  [CHARACTER_CLOTH_TYPE.ROBE]: {
    variant: CHARACTER_CLOTH_TYPE.ROBE,
    stylemap: cloth_robe_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.FEMALE],
    },
  },
};
