export enum CHARACTER_CLOTH_TYPE {
  NONE = "",
  CHILD_TSHIRT = "child_tshirt",
  LONGSLEEVE_SHIRT = "longsleeve_shirt",
  SCOOP = "scoop",
  COLORED_FORMAL_LONGSLEEVE = "colored_formal_longsleeve",
  STRIPED_FORMAL_LONGSLEEVE = "striped_formal_longsleeve",
  LONGSLEEVE_LACED = "longsleeve_laced",
  SHORTSLEEVE_SHIRT = "shortsleeve_shirt",
  TSHIRT = "tshirt",
  TSHIRT_VNECK = "tshirt_vneck",
  TSHIRT_SCOOP = "tshirt_scoop",
  TSHIRT_BUTTONED = "tshirt_buttoned",
  SLEEVELESS_SHIRT = "sleeveless_shirt",
  SLEEVELESS_LACED = "sleeveless_laced",
  SLEEVELESS_STRIPED = "sleeveless_striped",
  TANKTOP = "tanktop",
  SLEEVELESS2 = "sleeveless2",
  SLEEVELESS2_VNECK = "sleeveless2_vneck",
  SLEEVELESS2_SCOOP = "sleeveless2_scoop",
  SLEEVELESS2_BUTTONED = "sleeveless2_buttoned",
  BLOUSE = "blouse",
  LONGSLEEVE_BLOUSE = "longsleeve_blouse",
  TUNIC = "tunic",
  SARA_TUNIC = "sara_tunic",
  ROBE = "robe",
  APRON = "apron",
}