import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import {
  CHARACTER_HAIR_TYPE,
  CHARACTER_HAIR_EXTENSION_TYPE,
  CHARACTER_HORNS_TYPE,
  CHARACTER_FINS_TYPE
} from "./types";

export const hair_stylemap = [
  CHARACTER_STYLE.BLONDE,
  CHARACTER_STYLE.ASH,
  CHARACTER_STYLE.SANDY,
  CHARACTER_STYLE.PLATINUM,
  CHARACTER_STYLE.STRAWBERRY,
  CHARACTER_STYLE.REDHEAD,
  CHARACTER_STYLE.GINGER,
  CHARACTER_STYLE.CARROT,
  CHARACTER_STYLE.CHESTNUT,
  CHARACTER_STYLE.LIGHT_BROWN,
  CHARACTER_STYLE.DARK_BROWN,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.RAVEN,
  CHARACTER_STYLE.DARK_GRAY,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.VIOLET,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.ROSE,
];

export const hair_long_straight_stylemap = [
  CHARACTER_STYLE.ASHBLONDE,
  CHARACTER_STYLE.ASHPLATINUM,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLONDE,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.BROWN2,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED
]

export const hair_feature: CharacterFeature = {
  [CHARACTER_HAIR_TYPE.NONE]: {
    variant: CHARACTER_HAIR_TYPE.NONE,
    stylemap: [],
    required: {},
  },

  [CHARACTER_HAIR_TYPE.AFRO]: {
    variant: CHARACTER_HAIR_TYPE.AFRO,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.AFRO_NATURAL]: {
    variant: CHARACTER_HAIR_TYPE.AFRO_NATURAL,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.AFRO_DREADLOCKS_SHORT]: {
    variant: CHARACTER_HAIR_TYPE.AFRO_DREADLOCKS_SHORT,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.AFRO_DREADLOCKS_LONG]: {
    variant: CHARACTER_HAIR_TYPE.AFRO_DREADLOCKS_LONG,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.AFRO_TWISTS_FADE]: {
    variant: CHARACTER_HAIR_TYPE.AFRO_TWISTS_FADE,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.AFRO_TWISTS_STRAIGHT]: {
    variant: CHARACTER_HAIR_TYPE.AFRO_TWISTS_STRAIGHT,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.AFRO_FLAT_TOP_FADE]: {
    variant: CHARACTER_HAIR_TYPE.AFRO_FLAT_TOP_FADE,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.AFRO_FLAT_TOP_STRAIGHT]: {
    variant: CHARACTER_HAIR_TYPE.AFRO_FLAT_TOP_STRAIGHT,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.AFRO_CORNROWS]: {
    variant: CHARACTER_HAIR_TYPE.AFRO_CORNROWS,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },

  [CHARACTER_HAIR_TYPE.CURLY_JEWFRO]: {
    variant: CHARACTER_HAIR_TYPE.CURLY_JEWFRO,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.CURLY_SHROT]: {
    variant: CHARACTER_HAIR_TYPE.CURLY_SHROT,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.CURLY_LONG]: {
    variant: CHARACTER_HAIR_TYPE.CURLY_LONG,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },

  [CHARACTER_HAIR_TYPE.BALD_SHAVED_BALDING]: {
    variant: CHARACTER_HAIR_TYPE.BALD_SHAVED_BALDING,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BALD_SHAVED_LONGHAWK]: {
    variant: CHARACTER_HAIR_TYPE.BALD_SHAVED_LONGHAWK,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BALD_SHAVED_SHORTHAWK]: {
    variant: CHARACTER_HAIR_TYPE.BALD_SHAVED_SHORTHAWK,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BALD_SHAVED_HIGH_TIGHT]: {
    variant: CHARACTER_HAIR_TYPE.BALD_SHAVED_HIGH_TIGHT,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BALD_SHAVED_BUZZCUT]: {
    variant: CHARACTER_HAIR_TYPE.BALD_SHAVED_BUZZCUT,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },

  [CHARACTER_HAIR_TYPE.SHORT_PLAIN]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_PLAIN,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_PIXIE]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_PIXIE,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_PAGE]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_PAGE,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_PAGE2]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_PAGE2,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_IDOL]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_IDOL,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_MOP]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_MOP,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_PARTED]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_PARTED,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_PART2]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_PART2,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_MESSY1]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_MESSY1,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_MESSY2]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_MESSY2,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_MESSY3]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_MESSY3,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_BEDHEAD]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_BEDHEAD,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_UNKEMPT]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_UNKEMPT,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_BANGSSHORT]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_BANGSSHORT,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_SWOOP]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_SWOOP,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_SIDE_SWOOP]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_SIDE_SWOOP,
    stylemap: hair_stylemap,
    required: {},
  },
  [CHARACTER_HAIR_TYPE.SHORT_CURTAINS]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_CURTAINS,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_BANGS]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_BANGS,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_SINGLE]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_SINGLE,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_COWLICK]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_COWLICK,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_COWLICK_TALL]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_COWLICK_TALL,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SHORT_TIED_BACK]: {
    variant: CHARACTER_HAIR_TYPE.SHORT_TIED_BACK,
    stylemap: hair_stylemap,
    required: {},
  },

  [CHARACTER_HAIR_TYPE.SPIKY_SPIKED_PORCUPINE]: {
    variant: CHARACTER_HAIR_TYPE.SPIKY_SPIKED_PORCUPINE,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SPIKY_SPIKED_LIBERTY]: {
    variant: CHARACTER_HAIR_TYPE.SPIKY_SPIKED_LIBERTY,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SPIKY_SPIKED_LIBERTY2]: {
    variant: CHARACTER_HAIR_TYPE.SPIKY_SPIKED_LIBERTY2,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SPIKY_SPIKED_BEEHIVE]: {
    variant: CHARACTER_HAIR_TYPE.SPIKY_SPIKED_BEEHIVE,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SPIKY_SPIKED]: {
    variant: CHARACTER_HAIR_TYPE.SPIKY_SPIKED,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SPIKY_SPIKED2]: {
    variant: CHARACTER_HAIR_TYPE.SPIKY_SPIKED2,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.SPIKY_HALFMESSY]: {
    variant: CHARACTER_HAIR_TYPE.SPIKY_HALFMESSY,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },

  [CHARACTER_HAIR_TYPE.PIGTAILS]: {
    variant: CHARACTER_HAIR_TYPE.PIGTAILS,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.PIGTAILS_BUNCHES]: {
    variant: CHARACTER_HAIR_TYPE.PIGTAILS_BUNCHES,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.PIGTAILS_BANGS]: {
    variant: CHARACTER_HAIR_TYPE.PIGTAILS_BANGS,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },

  [CHARACTER_HAIR_TYPE.BOB]: {
    variant: CHARACTER_HAIR_TYPE.BOB,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BOB_LOB]: {
    variant: CHARACTER_HAIR_TYPE.BOB_LOB,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BOB_SIDE_PART]: {
    variant: CHARACTER_HAIR_TYPE.BOB_SIDE_PART,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },

  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_HALF_UP]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_HALF_UP,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_BANGS_BUN]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_BANGS_BUN,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_SHORTKNOT]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_SHORTKNOT,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_LONGKNOT]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_LONGKNOT,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_PONYTAIL]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_PONYTAIL,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_PONYTAIL2]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_PONYTAIL2,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_HIGH_PONY_TAIL]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_HIGH_PONY_TAIL,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_BRAID]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_BRAID,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_BRAID2]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_BRAID2,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_SHOULDER_LEFT]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_SHOULDER_LEFT,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_SHOUDLER_RIGHT]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_SHOUDLER_RIGHT,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_LONG_TIED]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_LONG_TIED,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_XLONG_PONYTAIL]: {
    variant: CHARACTER_HAIR_TYPE.BRAIDS_PONYTAILS_UPDOS_XLONG_PONYTAIL,
    stylemap: hair_stylemap,
    required: {},
  },

  [CHARACTER_HAIR_TYPE.LONG]: {
    variant: CHARACTER_HAIR_TYPE.LONG,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.LONG_LOOSE]: {
    variant: CHARACTER_HAIR_TYPE.LONG_LOOSE,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.LONG_BANGSLONG]: {
    variant: CHARACTER_HAIR_TYPE.LONG_BANGSLONG,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.LONG_BANGSLONG2]: {
    variant: CHARACTER_HAIR_TYPE.LONG_BANGSLONG2,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.LONG_MESSY]: {
    variant: CHARACTER_HAIR_TYPE.LONG_MESSY,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.LONG_MESSY2]: {
    variant: CHARACTER_HAIR_TYPE.LONG_MESSY2,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.LONG_CURTAINS_LONG]: {
    variant: CHARACTER_HAIR_TYPE.LONG_CURTAINS_LONG,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.LONG_WAVY]: {
    variant: CHARACTER_HAIR_TYPE.LONG_WAVY,
    stylemap: hair_stylemap,
    required: {},
  },
  [CHARACTER_HAIR_TYPE.LONG_LONG_CENTER_PART]: {
    variant: CHARACTER_HAIR_TYPE.LONG_LONG_CENTER_PART,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.LONG_STRAIGHT]: {
    variant: CHARACTER_HAIR_TYPE.LONG_STRAIGHT,
    stylemap: hair_long_straight_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },

  [CHARACTER_HAIR_TYPE.VERY_LONG_PRINESS]: {
    variant: CHARACTER_HAIR_TYPE.VERY_LONG_PRINESS,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.VERY_LONG_SARA]: {
    variant: CHARACTER_HAIR_TYPE.VERY_LONG_SARA,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.VERY_LONG_BAND]: {
    variant: CHARACTER_HAIR_TYPE.VERY_LONG_BAND,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HAIR_TYPE.VERY_LONG_XLONG]: {
    variant: CHARACTER_HAIR_TYPE.VERY_LONG_XLONG,
    stylemap: hair_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
};

export const hair_extension_stylemap = [
  CHARACTER_STYLE.BLONDE,
  CHARACTER_STYLE.ASH,
  CHARACTER_STYLE.SANDY,
  CHARACTER_STYLE.PLATINUM,
  CHARACTER_STYLE.STRAWBERRY,
  CHARACTER_STYLE.REDHEAD,
  CHARACTER_STYLE.GINGER,
  CHARACTER_STYLE.CARROT,
  CHARACTER_STYLE.CHESTNUT,
  CHARACTER_STYLE.LIGHT_BROWN,
  CHARACTER_STYLE.DARK_BROWN,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.RAVEN,
  CHARACTER_STYLE.DARK_GRAY,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.VIOLET,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.ROSE,
];

export const hair_extension_left_feature: CharacterFeature = {
  [CHARACTER_HAIR_EXTENSION_TYPE.NONE]: {
    variant: CHARACTER_HAIR_EXTENSION_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_HAIR_EXTENSION_TYPE.BRAID]: {
    variant: CHARACTER_HAIR_EXTENSION_TYPE.BRAID,
    stylemap: hair_extension_stylemap,
    required: {},
  },
  [CHARACTER_HAIR_EXTENSION_TYPE.XLONG_BANG]: {
    variant: CHARACTER_HAIR_EXTENSION_TYPE.XLONG_BANG,
    stylemap: hair_extension_stylemap,
    required: {},
  },
  [CHARACTER_HAIR_EXTENSION_TYPE.XLONG_BRAID]: {
    variant: CHARACTER_HAIR_EXTENSION_TYPE.XLONG_BRAID,
    stylemap: hair_extension_stylemap,
    required: {},
  },
};

export const hair_extension_right_feature: CharacterFeature = {
  [CHARACTER_HAIR_EXTENSION_TYPE.NONE]: {
    variant: CHARACTER_HAIR_EXTENSION_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_HAIR_EXTENSION_TYPE.BRAID]: {
    variant: CHARACTER_HAIR_EXTENSION_TYPE.BRAID,
    stylemap: hair_extension_stylemap,
    required: {},
  },
  [CHARACTER_HAIR_EXTENSION_TYPE.XLONG_BANG]: {
    variant: CHARACTER_HAIR_EXTENSION_TYPE.XLONG_BANG,
    stylemap: hair_extension_stylemap,
    required: {},
  },
  [CHARACTER_HAIR_EXTENSION_TYPE.XLONG_BRAID]: {
    variant: CHARACTER_HAIR_EXTENSION_TYPE.XLONG_BRAID,
    stylemap: hair_extension_stylemap,
    required: {},
  },
};

export const horns_stylemap = [
  CHARACTER_STYLE.HORNS,
  CHARACTER_STYLE.BLONDE,
  CHARACTER_STYLE.ASH,
  CHARACTER_STYLE.SANDY,
  CHARACTER_STYLE.PLATINUM,
  CHARACTER_STYLE.STRAWBERRY,
  CHARACTER_STYLE.REDHEAD,
  CHARACTER_STYLE.GINGER,
  CHARACTER_STYLE.CARROT,
  CHARACTER_STYLE.CHESTNUT,
  CHARACTER_STYLE.LIGHT_BROWN,
  CHARACTER_STYLE.DARK_BROWN,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.RAVEN,
  CHARACTER_STYLE.DARK_GRAY,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.VIOLET,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.LIGHT,
  CHARACTER_STYLE.AMBER,
  CHARACTER_STYLE.OLIVE,
  CHARACTER_STYLE.TAUPE,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.SKIN_BLACK,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.SKIN_BLUE,
  CHARACTER_STYLE.ZOMBIE_GREEN,
  CHARACTER_STYLE.SKIN_GREEN,
  CHARACTER_STYLE.PALE_GREEN,
  CHARACTER_STYLE.BRIGHT_GREEN,
  CHARACTER_STYLE.DARK_GREEN,
  CHARACTER_STYLE.FUR_BLACK,
  CHARACTER_STYLE.FUR_BROWN,
  CHARACTER_STYLE.FUR_TAN,
  CHARACTER_STYLE.FUR_COPPER,
  CHARACTER_STYLE.FUR_GOLD,
  CHARACTER_STYLE.FUR_GREY,
  CHARACTER_STYLE.FUR_WHITE,
  CHARACTER_STYLE.ZOMBIE,
  CHARACTER_STYLE.METALLIC_STEEL,
  CHARACTER_STYLE.METALLIC_IRON,
  CHARACTER_STYLE.METALLIC_CERAMIC,
  CHARACTER_STYLE.METALLIC_BRASS,
  CHARACTER_STYLE.METALLIC_COPPER,
  CHARACTER_STYLE.METALLIC_BRONZE,
  CHARACTER_STYLE.METALLIC_SILVER,
  CHARACTER_STYLE.METALLIC_GOLD
];

export const horns_feature: CharacterFeature = {
  [CHARACTER_HORNS_TYPE.NONE]: {
    variant: CHARACTER_HORNS_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_HORNS_TYPE.BACKWARDS_HORNS]: {
    variant: CHARACTER_HORNS_TYPE.BACKWARDS_HORNS,
    stylemap: horns_stylemap,
    required: {},
  },
  [CHARACTER_HORNS_TYPE.CURLED_HORNS]: {
    variant: CHARACTER_HORNS_TYPE.CURLED_HORNS,
    stylemap: horns_stylemap,
    required: {},
  },
};

export const fins_stylemap = [
  CHARACTER_STYLE.LIGHT,
  CHARACTER_STYLE.AMBER,
  CHARACTER_STYLE.OLIVE,
  CHARACTER_STYLE.TAUPE,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.ZOMBIE_GREEN,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.PALE_GREEN,
  CHARACTER_STYLE.BRIGHT_GREEN,
  CHARACTER_STYLE.DARK_GREEN,
  CHARACTER_STYLE.FUR_BLACK,
  CHARACTER_STYLE.FUR_BROWN,
  CHARACTER_STYLE.FUR_TAN,
  CHARACTER_STYLE.FUR_COPPER,
  CHARACTER_STYLE.FUR_GOLD,
  CHARACTER_STYLE.FUR_GREY,
  CHARACTER_STYLE.FUR_WHITE
];

export const fins_feature: CharacterFeature = {
  [CHARACTER_FINS_TYPE.NONE]: {
    variant: CHARACTER_FINS_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_FINS_TYPE.FIN]: {
    variant: CHARACTER_FINS_TYPE.FIN,
    stylemap: fins_stylemap,
    required: {},
  },
  [CHARACTER_FINS_TYPE.SHORT_FIN]: {
    variant: CHARACTER_FINS_TYPE.SHORT_FIN,
    stylemap: fins_stylemap,
    required: {},
  },
};
