import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";

import { CHARACTER_EYES_TYPE } from "../eyes/types";
import { CHARACTER_FACIAL_MASK_TYPE } from "./types";

export const facial_mask_stylemap = [
  CHARACTER_STYLE.DARK,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.YELLOW,
  CHARACTER_STYLE.STEEL,
  CHARACTER_STYLE.IRON,
  CHARACTER_STYLE.CERAMIC,
  CHARACTER_STYLE.BRASS,
  CHARACTER_STYLE.COPPER,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.GOLD,
];

export const facial_mask_feature: CharacterFeature = {
  [CHARACTER_FACIAL_MASK_TYPE.NONE]: {
    variant: CHARACTER_FACIAL_MASK_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_FACIAL_MASK_TYPE.MASK]: {
    variant: CHARACTER_FACIAL_MASK_TYPE.MASK,
    stylemap: facial_mask_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
};
