import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";

import {
  CHARACTER_FURRY_EARS_TYPE,
  CHARACTER_FURRY_EARS_SKIN_TYPE,
} from "./types";

export const furry_ears_stylemap = [
  CHARACTER_STYLE.BLONDE,
  CHARACTER_STYLE.ASH,
  CHARACTER_STYLE.SANDY,
  CHARACTER_STYLE.PLATINUM,
  CHARACTER_STYLE.STRAWBERRY,
  CHARACTER_STYLE.REDHEAD,
  CHARACTER_STYLE.GINGER,
  CHARACTER_STYLE.CARROT,
  CHARACTER_STYLE.CHESTNUT,
  CHARACTER_STYLE.LIGHT_BROWN,
  CHARACTER_STYLE.DARK_BROWN,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.RAVEN,
  CHARACTER_STYLE.DARK_GRAY,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.VIOLET,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.FUR_BLACK,
  CHARACTER_STYLE.FUR_BROWN,
  CHARACTER_STYLE.FUR_TAN,
  CHARACTER_STYLE.FUR_COPPER,
  CHARACTER_STYLE.FUR_GOLD,
  CHARACTER_STYLE.FUR_GREY,
  CHARACTER_STYLE.FUR_WHITE,
];

export const furry_ears_feature: CharacterFeature = {
  [CHARACTER_FURRY_EARS_TYPE.NONE]: {
    variant: CHARACTER_FURRY_EARS_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_FURRY_EARS_TYPE.CAT]: {
    variant: CHARACTER_FURRY_EARS_TYPE.CAT,
    stylemap: furry_ears_stylemap,
    required: {},
  },
  [CHARACTER_FURRY_EARS_TYPE.WOLF]: {
    variant: CHARACTER_FURRY_EARS_TYPE.WOLF,
    stylemap: furry_ears_stylemap,
    required: {},
  },
};

export const furry_ears_skin_stylemap = [
  CHARACTER_STYLE.LIGHT,
  CHARACTER_STYLE.AMBER,
  CHARACTER_STYLE.OLIVE,
  CHARACTER_STYLE.TAUPE,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.ZOMBIE_GREEN,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.PALE_GREEN,
  CHARACTER_STYLE.BRIGHT_GREEN,
  CHARACTER_STYLE.DARK_GREEN,
  CHARACTER_STYLE.ZOMBIE,
  CHARACTER_STYLE.FUR_BLACK,
  CHARACTER_STYLE.FUR_BROWN,
  CHARACTER_STYLE.FUR_TAN,
  CHARACTER_STYLE.FUR_COPPER,
  CHARACTER_STYLE.FUR_GOLD,
  CHARACTER_STYLE.FUR_GREY,
  CHARACTER_STYLE.FUR_WHITE,
];

export const furry_ears_skin_feature: CharacterFeature = {
  [CHARACTER_FURRY_EARS_SKIN_TYPE.NONE]: {
    variant: CHARACTER_FURRY_EARS_SKIN_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_FURRY_EARS_SKIN_TYPE.CAT]: {
    variant: CHARACTER_FURRY_EARS_SKIN_TYPE.CAT,
    stylemap: furry_ears_skin_stylemap,
    required: {
      [CHARACTER_FEATURE.FURRY_EARS]: [CHARACTER_FURRY_EARS_TYPE.CAT],
    },
  },
  [CHARACTER_FURRY_EARS_SKIN_TYPE.WOLF]: {
    variant: CHARACTER_FURRY_EARS_SKIN_TYPE.WOLF,
    stylemap: furry_ears_skin_stylemap,
    required: {
      [CHARACTER_FEATURE.FURRY_EARS]: [CHARACTER_FURRY_EARS_TYPE.WOLF],
    },
  },
};
