import { CHARACTER_STYLE, CharacterFeature } from "../../definitions";

import { CHARACTER_EARRING_TYPE } from "./types";

export const earring_stylemap = [
  CHARACTER_STYLE.BASE,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
  CHARACTER_STYLE.STEEL,
  CHARACTER_STYLE.IRON,
  CHARACTER_STYLE.CERAMIC,
  CHARACTER_STYLE.BRASS,
  CHARACTER_STYLE.COPPER,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.GOLD,
];

export const earring_left_feature: CharacterFeature = {
  [CHARACTER_EARRING_TYPE.NONE]: {
    variant: CHARACTER_EARRING_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_EARRING_TYPE.EARRING]: {
    variant: CHARACTER_EARRING_TYPE.EARRING,
    stylemap: earring_stylemap,
    required: {},
  },
};

export const earring_right_feature: CharacterFeature = {
  [CHARACTER_EARRING_TYPE.NONE]: {
    variant: CHARACTER_EARRING_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_EARRING_TYPE.EARRING]: {
    variant: CHARACTER_EARRING_TYPE.EARRING,
    stylemap: earring_stylemap,
    required: {},
  },
};
