import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import {
  CHARACTER_DRESS_TYPE,
  CHARACTER_DRESS_TRIM_TYPE,
  CHARACTER_DRESS_SLEEVES_TYPE,
  CHARACTER_DRESS_SLEEVES_TRIM_TYPE,
} from "./types";

export const dress_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const dress_feature: CharacterFeature = {
  [CHARACTER_DRESS_TYPE.NONE]: {
    variant: CHARACTER_DRESS_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_DRESS_TYPE.SASH]: {
    variant: CHARACTER_DRESS_TYPE.SASH,
    stylemap: dress_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.FEMALE],
    },
  },
  [CHARACTER_DRESS_TYPE.SLIT]: {
    variant: CHARACTER_DRESS_TYPE.SLIT,
    stylemap: dress_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.FEMALE],
    },
  },
  [CHARACTER_DRESS_TYPE.KIMONO]: {
    variant: CHARACTER_DRESS_TYPE.KIMONO,
    stylemap: dress_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_DRESS_TYPE.SPLIT_KIMONO]: {
    variant: CHARACTER_DRESS_TYPE.SPLIT_KIMONO,
    stylemap: dress_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
};

export const dress_trim_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const dress_trim_feature: CharacterFeature = {
  [CHARACTER_DRESS_TRIM_TYPE.NONE]: {
    variant: CHARACTER_DRESS_TRIM_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_DRESS_TRIM_TYPE.KIMONO]: {
    variant: CHARACTER_DRESS_TRIM_TYPE.KIMONO,
    stylemap: dress_stylemap,
    required: {
      [CHARACTER_FEATURE.DRESS]: [
        CHARACTER_DRESS_TYPE.KIMONO,
        CHARACTER_DRESS_TYPE.SPLIT_KIMONO,
      ],
    },
  },
  [CHARACTER_DRESS_TRIM_TYPE.SPLIT_KIMONO]: {
    variant: CHARACTER_DRESS_TRIM_TYPE.SPLIT_KIMONO,
    stylemap: dress_stylemap,
    required: {
      [CHARACTER_FEATURE.DRESS]: [
        CHARACTER_DRESS_TYPE.KIMONO,
        CHARACTER_DRESS_TYPE.SPLIT_KIMONO,
      ],
    },
  },
};

export const dress_sleeves_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const dress_sleeves_feature: CharacterFeature = {
  [CHARACTER_DRESS_SLEEVES_TYPE.NONE]: {
    variant: CHARACTER_DRESS_SLEEVES_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_DRESS_SLEEVES_TYPE.KIMONO]: {
    variant: CHARACTER_DRESS_SLEEVES_TYPE.KIMONO,
    stylemap: dress_sleeves_stylemap,
    required: {
      [CHARACTER_FEATURE.DRESS]: [
        CHARACTER_DRESS_TYPE.KIMONO,
        CHARACTER_DRESS_TYPE.SPLIT_KIMONO,
      ],
    },
  },
  [CHARACTER_DRESS_SLEEVES_TYPE.KIMONO_OVERSIZED]: {
    variant: CHARACTER_DRESS_SLEEVES_TYPE.KIMONO_OVERSIZED,
    stylemap: dress_sleeves_stylemap,
    required: {
      [CHARACTER_FEATURE.DRESS]: [
        CHARACTER_DRESS_TYPE.KIMONO,
        CHARACTER_DRESS_TYPE.SPLIT_KIMONO,
      ],
    },
  },
};

export const dress_sleeves_trim_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const dress_sleeves_trim_feature: CharacterFeature = {
  [CHARACTER_DRESS_SLEEVES_TRIM_TYPE.NONE]: {
    variant: CHARACTER_DRESS_SLEEVES_TRIM_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_DRESS_SLEEVES_TRIM_TYPE.KIMONO]: {
    variant: CHARACTER_DRESS_SLEEVES_TRIM_TYPE.KIMONO,
    stylemap: dress_sleeves_trim_stylemap,
    required: {
      [CHARACTER_FEATURE.DRESS_SLEEVES]: [CHARACTER_DRESS_SLEEVES_TYPE.KIMONO],
    },
  },
  [CHARACTER_DRESS_SLEEVES_TRIM_TYPE.KIMONO_OVERSIZED]: {
    variant: CHARACTER_DRESS_SLEEVES_TRIM_TYPE.KIMONO_OVERSIZED,
    stylemap: dress_sleeves_trim_stylemap,
    required: {
      [CHARACTER_FEATURE.DRESS_SLEEVES]: [
        CHARACTER_DRESS_SLEEVES_TYPE.KIMONO_OVERSIZED,
      ],
    },
  },
};
