import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import { CHARACTER_WRINKLES_TYPE } from "./types";

export const wrinkles_stylemap = [
  CHARACTER_STYLE.LIGHT,
  CHARACTER_STYLE.AMBER,
  CHARACTER_STYLE.OLIVE,
  CHARACTER_STYLE.TAUPE,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.ZOMBIE_GREEN,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.PALE_GREEN,
  CHARACTER_STYLE.BRIGHT_GREEN,
  CHARACTER_STYLE.DARK_GREEN,
  CHARACTER_STYLE.FUR_BLACK,
  CHARACTER_STYLE.FUR_BROWN,
  CHARACTER_STYLE.FUR_TAN,
  CHARACTER_STYLE.FUR_COPPER,
  CHARACTER_STYLE.FUR_GOLD,
  CHARACTER_STYLE.FUR_GREY,
  CHARACTER_STYLE.FUR_WHITE,
  CHARACTER_STYLE.ZOMBIE
];

export const wrinkles_feature: CharacterFeature = {
  [CHARACTER_WRINKLES_TYPE.NONE]: {
    variant: CHARACTER_WRINKLES_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_WRINKLES_TYPE.WRINKLES]: {
    variant: CHARACTER_WRINKLES_TYPE.WRINKLES,
    stylemap: wrinkles_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
};
