import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import {
  CHARACTER_BELT_TYPE,
  CHARACTER_SASH_TYPE,
  CHARACTER_SASH_TIE_TYPE,
  CHARACTER_SASH_OBI_TYPE,
} from "./types";

export const belt_stylemap = [
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
];

export const belt_other_female_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.IRON,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WHITE,
];

export const belt_other_male_stylemap = [
  CHARACTER_STYLE.FORMAL,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.WHITE,
];

export const belt_feature: CharacterFeature = {
  [CHARACTER_BELT_TYPE.NONE]: {
    variant: CHARACTER_BELT_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_BELT_TYPE.LEATHER]: {
    variant: CHARACTER_BELT_TYPE.LEATHER,
    stylemap: belt_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_BELT_TYPE.DOUBLE]: {
    variant: CHARACTER_BELT_TYPE.DOUBLE,
    stylemap: belt_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_BELT_TYPE.LOOSE]: {
    variant: CHARACTER_BELT_TYPE.LOOSE,
    stylemap: belt_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_BELT_TYPE.BELLY]: {
    variant: CHARACTER_BELT_TYPE.BELLY,
    stylemap: belt_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_BELT_TYPE.OTHER_FEMALE]: {
    variant: CHARACTER_BELT_TYPE.OTHER_FEMALE,
    stylemap: belt_other_female_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.FEMALE],
    },
  },
  [CHARACTER_BELT_TYPE.OTHER_MALE]: {
    variant: CHARACTER_BELT_TYPE.OTHER_MALE,
    stylemap: belt_other_male_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.MALE],
    },
  },
};

export const sash_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const sash_feature: CharacterFeature = {
  [CHARACTER_SASH_TYPE.NONE]: {
    variant: CHARACTER_SASH_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_SASH_TYPE.SASH]: {
    variant: CHARACTER_SASH_TYPE.SASH,
    stylemap: sash_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_SASH_TYPE.NARROW]: {
    variant: CHARACTER_SASH_TYPE.NARROW,
    stylemap: sash_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_SASH_TYPE.WAISTBAND]: {
    variant: CHARACTER_SASH_TYPE.WAISTBAND,
    stylemap: sash_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_SASH_TYPE.OBI]: {
    variant: CHARACTER_SASH_TYPE.OBI,
    stylemap: sash_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
};

export const sash_tie_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const sash_tie_feature: CharacterFeature = {
  [CHARACTER_SASH_TIE_TYPE.NONE]: {
    variant: CHARACTER_SASH_TIE_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_SASH_TIE_TYPE.OBI]: {
    variant: CHARACTER_SASH_TIE_TYPE.OBI,
    stylemap: sash_stylemap,
    required: {
      [CHARACTER_FEATURE.SASH]: [CHARACTER_SASH_TYPE.OBI],
    },
  },
};

export const sash_obi_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const sash_obi_feature: CharacterFeature = {
  [CHARACTER_SASH_OBI_TYPE.NONE]: {
    variant: CHARACTER_SASH_OBI_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_SASH_OBI_TYPE.OBI]: {
    variant: CHARACTER_SASH_OBI_TYPE.OBI,
    stylemap: sash_stylemap,
    required: {
      [CHARACTER_FEATURE.SASH]: [CHARACTER_SASH_TYPE.OBI],
    },
  },
};
