import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import { CHARACTER_HEAD_TYPE } from "./types";

export const head_stylemap = [
  CHARACTER_STYLE.LIGHT,
  CHARACTER_STYLE.AMBER,
  CHARACTER_STYLE.OLIVE,
  CHARACTER_STYLE.TAUPE,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.ZOMBIE_GREEN,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.PALE_GREEN,
  CHARACTER_STYLE.BRIGHT_GREEN,
  CHARACTER_STYLE.DARK_GREEN,
  CHARACTER_STYLE.ZOMBIE,
  CHARACTER_STYLE.FUR_BLACK,
  CHARACTER_STYLE.FUR_BROWN,
  CHARACTER_STYLE.FUR_TAN,
  CHARACTER_STYLE.FUR_COPPER,
  CHARACTER_STYLE.FUR_GOLD,
  CHARACTER_STYLE.FUR_GREY,
  CHARACTER_STYLE.FUR_WHITE,
];

export const head_skeleton_stylemap = [CHARACTER_STYLE.SKELETON];

export const head_jack_stylemap = [CHARACTER_STYLE.JACK];

export const head_feature: CharacterFeature = {
  [CHARACTER_HEAD_TYPE.HUMAN_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.HUMAN_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_HEAD_TYPE.BOAR_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.BOAR_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_HEAD_TYPE.PIG_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.PIG_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_HEAD_TYPE.SHEEP_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.SHEEP_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_HEAD_TYPE.MINOTAUR_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.MINOTAUR_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_HEAD_TYPE.WOLF_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.WOLF_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_HEAD_TYPE.RABBIT_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.RABBIT_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_HEAD_TYPE.RAT_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.RAT_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_HEAD_TYPE.MOUSE_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.MOUSE_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_HEAD_TYPE.LIZARD_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.LIZARD_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_HEAD_TYPE.ORC_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.ORC_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_HEAD_TYPE.GOBLIN_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.GOBLIN_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },
  [CHARACTER_HEAD_TYPE.TROLL_CHILD]: {
    variant: CHARACTER_HEAD_TYPE.TROLL_CHILD,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [CHARACTER_PERSON_TYPE.CHILD],
    },
  },

  [CHARACTER_HEAD_TYPE.HUMAN_FEMALE]: {
    variant: CHARACTER_HEAD_TYPE.HUMAN_FEMALE,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.HUMAN_MALE]: {
    variant: CHARACTER_HEAD_TYPE.HUMAN_MALE,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.HUMAN_FEMALE_ELDERLY]: {
    variant: CHARACTER_HEAD_TYPE.HUMAN_FEMALE_ELDERLY,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.HUMAN_MALE_ELDERLY]: {
    variant: CHARACTER_HEAD_TYPE.HUMAN_MALE_ELDERLY,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.HUMAN_MALE_PLUMP]: {
    variant: CHARACTER_HEAD_TYPE.HUMAN_MALE_PLUMP,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.HUMAN_MALE_GAUNT]: {
    variant: CHARACTER_HEAD_TYPE.HUMAN_MALE_GAUNT,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.BOAR]: {
    variant: CHARACTER_HEAD_TYPE.BOAR,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.PIG]: {
    variant: CHARACTER_HEAD_TYPE.PIG,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.SHEEP]: {
    variant: CHARACTER_HEAD_TYPE.SHEEP,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.MINOTAUR]: {
    variant: CHARACTER_HEAD_TYPE.MINOTAUR,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.MINOTAUR_FEMALE]: {
    variant: CHARACTER_HEAD_TYPE.MINOTAUR_FEMALE,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.WARTOTAUR]: {
    variant: CHARACTER_HEAD_TYPE.WARTOTAUR,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.WOLF_FEMALE]: {
    variant: CHARACTER_HEAD_TYPE.WOLF_FEMALE,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.WOLF_MALE]: {
    variant: CHARACTER_HEAD_TYPE.WOLF_MALE,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.RABBIT]: {
    variant: CHARACTER_HEAD_TYPE.RABBIT,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.RAT]: {
    variant: CHARACTER_HEAD_TYPE.RAT,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.MOUSE]: {
    variant: CHARACTER_HEAD_TYPE.MOUSE,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.LIZARD_FEMALE]: {
    variant: CHARACTER_HEAD_TYPE.LIZARD_FEMALE,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.LIZARD_MALE]: {
    variant: CHARACTER_HEAD_TYPE.LIZARD_MALE,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.ORC_FEMALE]: {
    variant: CHARACTER_HEAD_TYPE.ORC_FEMALE,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.ORC_MALE]: {
    variant: CHARACTER_HEAD_TYPE.ORC_MALE,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.GOBLIN]: {
    variant: CHARACTER_HEAD_TYPE.GOBLIN,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.ALIEN]: {
    variant: CHARACTER_HEAD_TYPE.ALIEN,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.TROLL]: {
    variant: CHARACTER_HEAD_TYPE.TROLL,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.SKELETON]: {
    variant: CHARACTER_HEAD_TYPE.SKELETON,
    stylemap: head_skeleton_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.ZOMBIE]: {
    variant: CHARACTER_HEAD_TYPE.ZOMBIE,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.JACK_O_LANTERN]: {
    variant: CHARACTER_HEAD_TYPE.JACK_O_LANTERN,
    stylemap: head_jack_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.VAMPIRE]: {
    variant: CHARACTER_HEAD_TYPE.VAMPIRE,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_HEAD_TYPE.FRANKENSTEIN]: {
    variant: CHARACTER_HEAD_TYPE.FRANKENSTEIN,
    stylemap: head_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
};
