import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_EYES_TYPE } from "../eyes/types";
import { CHARACTER_FACIAL_EYES_TYPE } from "./types";

export const facial_eyes_glasses_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
  CHARACTER_STYLE.STEEL,
  CHARACTER_STYLE.IRON,
  CHARACTER_STYLE.CERAMIC,
  CHARACTER_STYLE.BRASS,
  CHARACTER_STYLE.COPPER,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.GOLD,
];

export const facial_eyes_patch_stylemap = [
  CHARACTER_STYLE.BASE,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const facial_eyes_patch2_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const facial_eyes_feature: CharacterFeature = {
  [CHARACTER_FACIAL_EYES_TYPE.NONE]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_FACIAL_EYES_TYPE.GLASSES]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.GLASSES,
    stylemap: facial_eyes_glasses_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_FACIAL_EYES_TYPE.HALFMOON_GLASSES]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.HALFMOON_GLASSES,
    stylemap: facial_eyes_glasses_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_FACIAL_EYES_TYPE.NERD_GLASSES]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.NERD_GLASSES,
    stylemap: facial_eyes_glasses_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_FACIAL_EYES_TYPE.SHADE_GLASSES]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.SHADE_GLASSES,
    stylemap: facial_eyes_glasses_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_FACIAL_EYES_TYPE.SECRETARY_GLASSES]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.SECRETARY_GLASSES,
    stylemap: facial_eyes_glasses_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_FACIAL_EYES_TYPE.ROUND_GLASSES]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.ROUND_GLASSES,
    stylemap: facial_eyes_glasses_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_FACIAL_EYES_TYPE.SUNGLASSES]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.SUNGLASSES,
    stylemap: facial_eyes_glasses_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },

  [CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_AMBIDEXTROUS]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_AMBIDEXTROUS,
    stylemap: facial_eyes_patch_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_LEFT]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_LEFT,
    stylemap: facial_eyes_patch_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_RIGHT]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_RIGHT,
    stylemap: facial_eyes_patch_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_LEFT2]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_LEFT2,
    stylemap: facial_eyes_patch2_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_RIGHT2]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_RIGHT2,
    stylemap: facial_eyes_patch2_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_SMALL_LEFT]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_SMALL_LEFT,
    stylemap: facial_eyes_patch_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
  [CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_SMALL_RIGHT]: {
    variant: CHARACTER_FACIAL_EYES_TYPE.EYEPATCH_SMALL_RIGHT,
    stylemap: facial_eyes_patch_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
};
