import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import { CHARACTER_NECK_TYPE, CHARACTER_NECKLACE_TYPE } from "./types";

export const neck_tie_1_stylemap = [
  CHARACTER_STYLE.BASE,
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const neck_tie_2_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const neck_scarf_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.WHITE,
];

export const neck_feature: CharacterFeature = {
  [CHARACTER_NECK_TYPE.NONE]: {
    variant: CHARACTER_NECK_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_NECK_TYPE.BOWTIE]: {
    variant: CHARACTER_NECK_TYPE.BOWTIE,
    stylemap: neck_tie_1_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_NECK_TYPE.BOWTIE2]: {
    variant: CHARACTER_NECK_TYPE.BOWTIE2,
    stylemap: neck_tie_2_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_NECK_TYPE.NECKTIE]: {
    variant: CHARACTER_NECK_TYPE.NECKTIE,
    stylemap: neck_tie_1_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_NECK_TYPE.SCARF]: {
    variant: CHARACTER_NECK_TYPE.SCARF,
    stylemap: neck_scarf_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_NECK_TYPE.CAPECLIP]: {
    variant: CHARACTER_NECK_TYPE.CAPECLIP,
    stylemap: neck_tie_2_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_NECK_TYPE.CAPETIE]: {
    variant: CHARACTER_NECK_TYPE.CAPETIE,
    stylemap: neck_tie_2_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
  [CHARACTER_NECK_TYPE.JABOT]: {
    variant: CHARACTER_NECK_TYPE.JABOT,
    stylemap: neck_tie_2_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
  [CHARACTER_NECK_TYPE.CRAVAT]: {
    variant: CHARACTER_NECK_TYPE.CRAVAT,
    stylemap: neck_tie_2_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
      ],
    },
  },
};

export const necklace_stylemap = [
  CHARACTER_STYLE.STEEL,
  CHARACTER_STYLE.IRON,
  CHARACTER_STYLE.CERAMIC,
  CHARACTER_STYLE.BRASS,
  CHARACTER_STYLE.COPPER,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.GOLD,
  CHARACTER_STYLE.PIRATE,
];

export const necklace_feature: CharacterFeature = {
  [CHARACTER_NECKLACE_TYPE.NONE]: {
    variant: CHARACTER_NECKLACE_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_NECKLACE_TYPE.NECKLACE]: {
    variant: CHARACTER_NECKLACE_TYPE.NECKLACE,
    stylemap: necklace_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
};
