import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_EYES_TYPE } from "../eyes/types";

import {
  CHARACTER_FACIAL_LEFT_TYPE,
  CHARACTER_FACIAL_LEFT_TRIM_TYPE,
} from "./types";

export const facial_left_stylemap = [
  CHARACTER_STYLE.STEEL,
  CHARACTER_STYLE.IRON,
  CHARACTER_STYLE.CERAMIC,
  CHARACTER_STYLE.BRASS,
  CHARACTER_STYLE.COPPER,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.GOLD,
];

export const facial_left_feature: CharacterFeature = {
  [CHARACTER_FACIAL_LEFT_TYPE.NONE]: {
    variant: CHARACTER_FACIAL_LEFT_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_FACIAL_LEFT_TYPE.MONOCLE]: {
    variant: CHARACTER_FACIAL_LEFT_TYPE.MONOCLE,
    stylemap: facial_left_stylemap,
    required: {
      [CHARACTER_FEATURE.EYES]: [CHARACTER_EYES_TYPE.HUMAN],
    },
  },
};

export const facial_left_trim_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
  CHARACTER_STYLE.STEEL,
  CHARACTER_STYLE.IRON,
  CHARACTER_STYLE.CERAMIC,
  CHARACTER_STYLE.BRASS,
  CHARACTER_STYLE.COPPER,
  CHARACTER_STYLE.BRONZE,
  CHARACTER_STYLE.SILVER,
  CHARACTER_STYLE.GOLD,
];

export const facial_left_trim_feature: CharacterFeature = {
  [CHARACTER_FACIAL_LEFT_TRIM_TYPE.NONE]: {
    variant: CHARACTER_FACIAL_LEFT_TRIM_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_FACIAL_LEFT_TRIM_TYPE.MONOCLE]: {
    variant: CHARACTER_FACIAL_LEFT_TRIM_TYPE.MONOCLE,
    stylemap: facial_left_trim_stylemap,
    required: {
      [CHARACTER_FEATURE.FACIAL_LEFT]: [CHARACTER_FACIAL_LEFT_TYPE.MONOCLE],
    },
  },
};
