import {
  CHARACTER_STYLE,
  CHARACTER_FEATURE,
  CharacterFeature,
} from "../../definitions";
import { CHARACTER_PERSON_TYPE } from "../../person/definitions";

import {
  CHARACTER_HEADCOVER_TYPE,
  CHARACTER_HEADCOVER_RUNE_TYPE,
  CHARACTER_HAIRTIE_TYPE,
  CHARACTER_HAIRTIE_RUNE_TYPE,
  CHARACTER_BANDANA_TYPE,
} from "./types";

export const headcover_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const headcover_feature: CharacterFeature = {
  [CHARACTER_HEADCOVER_TYPE.NONE]: {
    variant: CHARACTER_HEADCOVER_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_HEADCOVER_TYPE.KERCHIEF]: {
    variant: CHARACTER_HEADCOVER_TYPE.KERCHIEF,
    stylemap: headcover_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
      ],
    },
  },
  [CHARACTER_HEADCOVER_TYPE.TIED_HEADBAND]: {
    variant: CHARACTER_HEADCOVER_TYPE.TIED_HEADBAND,
    stylemap: headcover_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
      ],
    },
  },
  [CHARACTER_HEADCOVER_TYPE.HEAD_COVERINGS_WOVERLAY_THICK_HEADBAND]: {
    variant: CHARACTER_HEADCOVER_TYPE.HEAD_COVERINGS_WOVERLAY_THICK_HEADBAND,
    stylemap: headcover_stylemap,
    required: {},
  },
};

export const headcover_rune_feature: CharacterFeature = {
  [CHARACTER_HEADCOVER_RUNE_TYPE.NONE]: {
    variant: CHARACTER_HEADCOVER_RUNE_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_HEADCOVER_RUNE_TYPE.HEAD_COVERINGS_WOVERLAY_THICK_HEADBAND_RUNE]: {
    variant:
      CHARACTER_HEADCOVER_RUNE_TYPE.HEAD_COVERINGS_WOVERLAY_THICK_HEADBAND_RUNE,
    stylemap: headcover_stylemap,
    required: {
      [CHARACTER_FEATURE.HEADCOVER]: [
        CHARACTER_HEADCOVER_TYPE.HEAD_COVERINGS_WOVERLAY_THICK_HEADBAND,
      ],
    },
  },
};

export const hairtie_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const hairtie_feature: CharacterFeature = {
  [CHARACTER_HAIRTIE_TYPE.NONE]: {
    variant: CHARACTER_HAIRTIE_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_HAIRTIE_TYPE.HEAD_COVERINGS_WOVERLAY_HAIRTIE]: {
    variant: CHARACTER_HAIRTIE_TYPE.HEAD_COVERINGS_WOVERLAY_HAIRTIE,
    stylemap: hairtie_stylemap,
    required: {},
  },
};

export const hairtie_rune_feature: CharacterFeature = {
  [CHARACTER_HAIRTIE_RUNE_TYPE.NONE]: {
    variant: CHARACTER_HAIRTIE_RUNE_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_HAIRTIE_RUNE_TYPE.HEAD_COVERINGS_WOVERLAY_HAIRTIE_RUNE]: {
    variant: CHARACTER_HAIRTIE_RUNE_TYPE.HEAD_COVERINGS_WOVERLAY_HAIRTIE_RUNE,
    stylemap: hairtie_stylemap,
    required: {
      [CHARACTER_FEATURE.HAIRTIE]: [
        CHARACTER_HAIRTIE_TYPE.HEAD_COVERINGS_WOVERLAY_HAIRTIE,
      ],
    },
  },
};

export const bandana_stylemap = [
  CHARACTER_STYLE.BLACK,
  CHARACTER_STYLE.BLUE,
  CHARACTER_STYLE.BLUEGRAY,
  CHARACTER_STYLE.BROWN,
  CHARACTER_STYLE.CHARCOAL,
  CHARACTER_STYLE.FOREST,
  CHARACTER_STYLE.GRAY,
  CHARACTER_STYLE.GREEN,
  CHARACTER_STYLE.LAVENDER,
  CHARACTER_STYLE.LEATHER,
  CHARACTER_STYLE.MAROON,
  CHARACTER_STYLE.NAVY,
  CHARACTER_STYLE.ORANGE,
  CHARACTER_STYLE.PINK,
  CHARACTER_STYLE.PURPLE,
  CHARACTER_STYLE.RED,
  CHARACTER_STYLE.ROSE,
  CHARACTER_STYLE.SKY,
  CHARACTER_STYLE.SLATE,
  CHARACTER_STYLE.TAN,
  CHARACTER_STYLE.TEAL,
  CHARACTER_STYLE.WALNUT,
  CHARACTER_STYLE.WHITE,
  CHARACTER_STYLE.YELLOW,
];

export const bandana_mail_stylemap = [
  CHARACTER_STYLE.STEEL
]

export const bandana_feature: CharacterFeature = {
  [CHARACTER_BANDANA_TYPE.NONE]: {
    variant: CHARACTER_BANDANA_TYPE.NONE,
    stylemap: [],
    required: {},
  },
  [CHARACTER_BANDANA_TYPE.BANDANA]: {
    variant: CHARACTER_BANDANA_TYPE.BANDANA,
    stylemap: bandana_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
      ],
    },
  },
  [CHARACTER_BANDANA_TYPE.SKULL_BANDANA]: {
    variant: CHARACTER_BANDANA_TYPE.SKULL_BANDANA,
    stylemap: bandana_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
      ],
    },
  },
  [CHARACTER_BANDANA_TYPE.MAIL]: {
    variant: CHARACTER_BANDANA_TYPE.MAIL,
    stylemap: bandana_mail_stylemap,
    required: {
      [CHARACTER_FEATURE.PERSON]: [
        CHARACTER_PERSON_TYPE.MALE,
        CHARACTER_PERSON_TYPE.FEMALE,
        CHARACTER_PERSON_TYPE.TEEN,
        CHARACTER_PERSON_TYPE.PREGNANT,
        CHARACTER_PERSON_TYPE.MUSCULAR,
      ],
    },
  },
};
